# Generated by Django 4.1.3 on 2022-11-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapi', '0002_people_planet_transport_species_people_homeworld_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='film',
            name='created',
        ),
        migrations.RemoveField(
            model_name='film',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='created',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='people',
            name='created',
        ),
        migrations.RemoveField(
            model_name='people',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='species',
            name='created',
        ),
        migrations.RemoveField(
            model_name='species',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='edited',
        ),
    ]
