# Generated by Django 4.1.3 on 2022-11-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapi', '0003_delete_cliente_remove_film_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
