# Generated by Django 4.1.3 on 2022-11-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapi', '0005_alter_people_homeworld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
